# Generated by Django 5.1.4 on 2025-01-13 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subject_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_images', to='blog.lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='blog.image'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='blog.post'),
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_code_snippets', to='blog.lesson')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_code_snippets', to='blog.post')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='code_snippets',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='blog.codesnippet'),
        ),
        migrations.AddField(
            model_name='post',
            name='code_snippets',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.codesnippet'),
        ),
    ]
