# Generated by Django 5.1.4 on 2025-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_menu_image_menu_slug_menuitem_image_alter_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
